name: 6.12.23 欧加真OKI内核快速构建

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android16'
  KERNEL_VERSION: '6.12'
  SUB_VERSION: '23'
  KERNEL_NAME: 'android16-5-ga8f88ad96df3-ab13929693-4k'
  CCACHE_KEY: ccache-ecsv2-6.12.23

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: 'KernelSU分支(ReSukiSU/SukiSU Ultra/KernelSU Next/KSU(原版)/无内置KSU,默认ReSukiSU)'
        required: true
        type: choice
        default: 'resukisu'
        options:
          - 'resukisu'
          - 'sukisu'
          - 'ksunext'
          - 'ksu'
          - 'none'
      susfs_enable:
        description: '是否开启susfs(用于增强隐藏环境挂载功能; 可能轻微增加耗电，上游更新导致不稳定时或不需要可关闭)'
        required: true
        type: boolean
        default: 'true'
      kpm_enable:
        description: '是否开启kpm(builtin-使用(re)sukisu内置kpm, kpn-使用独立kpm实现(支持任意KSU/面具环境); 不需要可保持默认关闭)'
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'builtin'
          - 'kpn'
      lz4_enable:
        description: '是否安装 lz4 1.10.0+zstd 1.5.7 补丁'
        required: true
        type: boolean
        default: 'true'
      lz4kd_enable:
        description: '是否安装 LZ4KD 补丁(若已开启lz4+zstd补丁则可不开启)'
        required: true
        type: boolean
        default: 'false'
      bbr_enable:
        description: "是否启用bbr算法(优化上行数据,对手机日用无太大意义甚至可能负优化;false关闭,true仅加入算法,default启用算法并设为默认)"
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      better_net:
        description: '是否开启网络功能拓展配置(用于为ipset及需要iptables等高级网络功能内核支持的程序提供支持)'
        required: true
        type: boolean
        default: 'false'
      adios_enable:
        description: '是否启用ADIOS IO调度器支持(提升IO读写性能)'
        required: true
        type: boolean
        default: 'true'
      rekernel_enable:
        description: '是否启用Re-Kernel支持(与Freezer/NoActive等软件配合, 提升应用冻结能力)'
        required: true
        type: boolean
        default: 'false'
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: 'true'
      ccache_update:
        description: '更新ccache缓存(将本次编译生成的ccache缓存覆盖至仓库缓存，在更改编译配置、源码或需要刷新缓存时开启)'
        required: true
        type: boolean
        default: 'false'
      ccache_debug:
        description: '是否上传 Ccache调试日志(用于调试, 无需要不必开启)'
        required: true
        type: boolean
        default: 'false'
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符,勿加空格等影响指令运行的保留字符)'
        required: false
        type: string
        default: ''
      droidspaces:
        description:'一款轻量级Linux容器工具'
        required: true
        type: boolean
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
      ak3name: ${{ steps.create_zip.outputs.ak3name }}
    permissions:
      actions: write
      contents: read
    steps:
      - name: 安装环境依赖+初始化源码仓库及llvm-clang19工具链
        run: |
          rm -rf kernel_workspace
          mkdir kernel_workspace
          cd kernel_workspace
          echo "当前仓库：$GITHUB_REPOSITORY"
          echo "当前分支：$GITHUB_REF_NAME"
          
          sudo apt-mark hold firefox &&
          sudo apt-mark hold libc-bin &&
          sudo apt purge man-db &&
          sudo rm -rf /var/lib/man-db/auto-update &&
          sudo apt update &&
          sudo apt-get install -y --no-install-recommends binutils python-is-python3 libssl-dev libelf-dev libdw-dev &
          #旧版完整指令：（由于经过验证大部分指令已内置于GitHub Action环境中，故进行精简）
          #sudo apt-get install -y --no-install-recommends curl bison flex make binutils git perl gcc python3 python-is-python3 bc libssl-dev libelf-dev libdw-dev zip unzip ccache
          
          #使用最新版ccache v4.12.2（Ubuntu软件仓库的版本并非最新）
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/ccache-x86-64 -O ccache &&
          sudo cp -f ./ccache /usr/bin/ccache &&
          sudo chmod +x /usr/bin/ccache &&
          rm -f ./ccache &
          
          echo "正在克隆源码仓库..."
          aria2c -s16 -x16 -k1M https://github.com/cctv18/android_kernel_common_oneplus_sm8850/archive/refs/heads/oneplus/sm8850_v_16.0.0_oneplus_15.zip -o common.zip && 
          unzip -q common.zip && 
          mv "android_kernel_common_oneplus_sm8850-oneplus-sm8850_v_16.0.0_oneplus_15" common &&
          rm -rf common.zip &
          
          echo "正在克隆llvm-clang19工具链..." &&
          mkdir -p clang19 &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang19-r536225/clang-r536225.zip -o clang.zip &&
          unzip -q clang.zip -d clang19 &&
          rm -rf clang.zip &
          
          echo "正在克隆Rust 1.82.0工具链..." &&
          mkdir -p rust &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang19-r536225/rust.zip -o rust.zip &&
          unzip 
